from __future__ import annotations

import io
import re

from docx import Document


def _safe_filename(task_id: str) -> str:
    slug = re.sub(r"[^a-zA-Z0-9_-]+", "-", task_id).strip("-") or "report"
    return f"research-report-{slug[:24]}"


def build_report_text(
    *,
    goal: str,
    report_body: str,
    sources: list[dict] | None,
    brand_name: str,
) -> str:
    lines = [
        f"{brand_name} — Research Report",
        "=" * 40,
        "",
        "Question",
        "-" * 8,
        goal,
        "",
        "Report",
        "-" * 6,
        report_body,
    ]
    if sources:
        lines.extend(["", "Sources", "-" * 7])
        for source in sources:
            name = source.get("filename") or source.get("source") or "Document"
            score = source.get("score")
            if score is not None:
                lines.append(f"- {name} (relevance {score:.2f})")
            else:
                lines.append(f"- {name}")
    lines.extend(["", f"Generated by {brand_name}"])
    return "\n".join(lines)


def build_report_docx(
    *,
    goal: str,
    report_body: str,
    sources: list[dict] | None,
    brand_name: str,
) -> bytes:
    doc = Document()
    doc.add_heading(f"{brand_name} — Research Report", level=0)
    doc.add_heading("Question", level=1)
    doc.add_paragraph(goal)
    doc.add_heading("Report", level=1)
    doc.add_paragraph(report_body)
    if sources:
        doc.add_heading("Sources", level=1)
        for source in sources:
            name = source.get("filename") or source.get("source") or "Document"
            score = source.get("score")
            text = f"{name} (relevance {score:.2f})" if score is not None else name
            doc.add_paragraph(text, style="List Bullet")
    buffer = io.BytesIO()
    doc.save(buffer)
    return buffer.getvalue()


def build_report_attachments(
    *,
    task_id: str,
    goal: str,
    report_body: str,
    sources: list[dict] | None,
    brand_name: str,
) -> list[tuple[str, bytes, str]]:
    base = _safe_filename(task_id)
    text = build_report_text(
        goal=goal,
        report_body=report_body,
        sources=sources,
        brand_name=brand_name,
    )
    docx = build_report_docx(
        goal=goal,
        report_body=report_body,
        sources=sources,
        brand_name=brand_name,
    )
    return [
        (f"{base}.txt", text.encode("utf-8"), "text/plain"),
        (
            f"{base}.docx",
            docx,
            "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        ),
    ]
